version: '3'

services:
  django:
    build: .
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Mount the SQLite database file
    ports:
      - "8000:8000"
    
